Assignment Questions - Numpy

In [36]:

# A Python library is a collection of related modules that contain bundles of code, documentation, configuration data, message templates, classes, and values. 
# These libraries are used to simplify and speed up programming by providing precompiled code that can be reused in different programs. Python libraries play 
# a crucial role in various fields such as Machine Learning, Data Science, and Data Visualization.



# We use Python libraries to avoid reinventing the wheel, as they provide pre-written collections of functions and modules that help developers access and use specific functionalities
# without having to create them from scratch. This saves time, increases productivity, and allows programmers to focus on solving unique problems rather than on basic tasks that have 
# already been solved by these libraries


In [37]:
# Numpy array stores homogenous data which helps in faster computation whereas List store heterogenous data .
# Numpy array is of fixed size means once defined it cannot be changed so it has no concept of resizing whereas list is of dynamic size means can be changed at any time so concept of resizing exits here

In [38]:
import numpy as np

l = [[1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]] 

arr = np.array(l)

print("Shape of Matrix :",arr.shape)
print("Size of Matrix :",arr.size)
print("Dimension of Matrix :",arr.ndim)

Shape of Matrix : (3, 4)
Size of Matrix : 12
Dimension of Matrix : 2


In [34]:
import numpy as np

l = [[1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]]

arr = np.array(l)

print("First row of array:",arr[0])

First row of array: [1 2 3 4]


In [39]:
import numpy as np

l = [[1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]]

arr = np.array(l)

print("element at the third row and fourth column :",arr[2][3])

element at the third row and fourth column : 12


In [40]:
import numpy as np

l = [[1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]]

arr = np.array(l)

odd = []

for i in range(len(arr)):
    for j in range(len(arr[0])):
        if (i+j) % 2 != 0:
                odd.append(arr[i][j])
                
print("all odd-indexed elements from the given numpy array :",odd)

all odd-indexed elements from the given numpy array : [2, 4, 5, 7, 10, 12]


In [41]:
import numpy as np
print("Below is a random 3x3 matrix with values between 0 and 1 :")
np.random.rand(3,3)

Below is a random 3x3 matrix with values between 0 and 1 :


array([[0.59201847, 0.57763316, 0.79057343],
       [0.44851764, 0.10407913, 0.6489327 ],
       [0.19184457, 0.11522765, 0.45763328]])

In [16]:
# np.random.rand generates random numbers from a uniform distribution between 0 and 1, while
# np.random.randn generates random numbers from a standard normal distribution (mean 0, standard deviation 1).

In [21]:
import numpy as np

l = [[1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]]

arr = np.array(l)

np.expand_dims(arr,axis=1) # expanding dimension columnwise

array([[[ 1,  2,  3,  4]],

       [[ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12]]])

In [10]:
import numpy as np

l = [[1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]]

arr = np.array(l)
print("Transpose Of Given Matrix :")
print(arr.T)

Transpose Of Given Matrix :
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [30]:
import numpy as np

# Define matrices A and B
A2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
B2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# 1. Index wise multiplication
index_wise_mult = A2 * B2

# 2. Matrix multiplication
matrix_mult = np.dot(A2, B2.T)  # or A2 @ B2.T

# 3. Add both matrices
matrix_sum = A2 + B2

# 4. Subtract matrix B from A
matrix_diff = A2 - B2

# 5. Divide Matrix B by A
matrix_div = B2 / A2

# Display results
print("Index wise multiplication:\n", index_wise_mult)
print("\nMatrix multiplication:\n", matrix_mult)
print("\nMatrix sum:\n", matrix_sum)
print("\nMatrix difference:\n", matrix_diff)
print("\nMatrix division:\n", matrix_div)


Index wise multiplication:
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

Matrix multiplication:
 [[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

Matrix sum:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

Matrix difference:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Matrix division:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [42]:
# The function in NumPy used to swap the byte order of an array is np.ndarray.byteswap(). This function toggles between
# low-endian and big-endian data representation by returning a byteswapped array, optionally swapped in-place. It's 
# important to note that arrays of byte-strings are not swapped, and the real and imaginary parts of a complex number are 
# swapped individually

In [7]:
# The np.linalg.inv function in NumPy is used to calculate the inverse of a matrix. The inverse of a matrix, when 
# multiplied by the original matrix, results in the identity matrix. This function is crucial in linear algebra for 
# solving systems of equations, among other applications

In [5]:
# np.reshape function reshapes the original array into another array of same size by changing number of number of rows 
# and columns of original array keeping in mind the size remains same . The usage of it stated below :

import numpy as np

l = [[1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]]

arr = np.array(l)

print("Original Array :")
print(arr)

print()

arr1 = np.reshape(arr,(4,3))
print("Reshaped Array :")
print(arr1)


Original Array :
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Reshaped Array :
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [6]:
# Broadcasting in NumPy refers to how NumPy handles operations between arrays of different shapes. It allows for 
# arithmetic operations between arrays of different sizes by automatically expanding the smaller array to match the 
# shape of the larger one, provided they meet certain constraints. This process enables vectorized operations, which are 
# more efficient than using Python loops, as they are implemented in C. However, broadcasting can lead to inefficient 
# memory use in some cases, slowing down computation. The resulting array from a broadcasting operation will have the same
# number of dimensions as the array with the most dimensions. Broadcasting can be applied to multiple arrays and is a 
# fundamental feature for performing arithmetic operations on arrays of different shapes efficiently